#Skater Template
skater_template<-c(
  "id",
  "gameID",
  "goals",
  "assists",
  "shots",
  "hits",
  "powerPlayGoals",
  "powerPlayAssists",
  "penaltyMinutes",
  "faceOffWins",
  "faceoffTaken",
  "faceOffPct",
  "takeaways",
  "giveaways",
  "shortHandedGoals",
  "shortHandedAssists",
  "blocked",
  "plusMinus",
  "timeOnIce",
  "evenTimeOnIce",
  "powerPlayTimeOnIce",
  "shortHandedTimeOnIce"
)

#Goalie Template
goalie_template<-c(
  "id",
  "gameID",
  "goals",
  "timeOnIce",
  "assists",
  "shots",
  "pim",
  "saves",
  "shots",
  "powerPlaySaves",
  "powerPlayShotsAgainst",
  "shortHandedSaves",
  "shortHandedShotsAgainst",
  "evenSaves",
  "evenShotsAgainst",
  "decision",
  "savePercentage",
  "powerPlaySavePercentage",
  "shortHandedSavePercentage",
  "evenStrengthSavePercentage"
)
